/** Events the indexer subscribes to, per contract. Every name must exist in that contract ABI (see test/config-events.spec.ts). */
export const CONTRACT_EVENTS: Record<string, readonly string[]> = {
  SeriesFactory: [
    "SeriesCreated",
    "PrimaryPriceRaised",
    "SeriesPaused",
    "SeriesUnpaused",
    "SeriesFinalized",
    "ArbitratorAllowlistUpdated",
    "GateUpdated",
    "RoleGranted",
    "RoleRevoked",
    "RoleAdminChanged",
  ],
  ProviderRegistry: ["ProviderRegistered", "ProviderStatusChanged", "ReputationUpdated", "RoleGranted", "RoleRevoked"],
  ConversionTable: ["FactorSet", "RoleGranted", "RoleRevoked"],
  BondVault: ["BondDeposited", "BondReleased", "BondSlashed", "BondFinalized", "BondWithdrawn"],
  PrimarySale: ["PrimaryBuy", "TreasuryUpdated", "PrimaryFeeUpdated", "GateUpdated", "RoleGranted", "RoleRevoked"],
  OrderBook: ["OrderPlaced", "OrderCancelled", "Trade", "TakerFeeUpdated", "GateUpdated", "IndexUpdateFailed", "RoleGranted", "RoleRevoked"],
  RedemptionManager: [
    "RedemptionRequested",
    "Acknowledged",
    "Delivered",
    "Disputed",
    "RedemptionFinalized",
    "Defaulted",
    "Refunded",
    "Ruled",
    "RedemptionReopened",
    "IndexUpdateFailed",
  ],
  PanelArbitrator: ["DisputeReceived", "RulingSubmitted", "PanelUpdated", "RoleGranted", "RoleRevoked"],
  PrintIndex: [
    "IndexUpdated",
    "IndexStatusChanged",
    "DeliveryRecorded",
    "DefaultRecorded",
    "IndexParamsUpdated",
    "PrintRecorded",
    "RoleGranted",
    "RoleRevoked",
  ],
  ReferenceFeed: ["ReferenceUpdated", "LabelUpdated", "RoleGranted", "RoleRevoked"],
  EASGate: ["AttestationLinked", "AttesterUpdated", "RoleGranted", "RoleRevoked"],
  RegistryGate: ["ParticipantSet", "ParticipantRevoked", "RoleGranted", "RoleRevoked"],
  EAS: ["Attested", "Revoked"],
  TimelockController: ["CallScheduled", "CallSalt", "CallExecuted", "Cancelled", "MinDelayChange", "RoleGranted", "RoleRevoked"],
  CUToken: ["Transfer"],
};
